CREATE TABLE mails (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    site_id INT UNSIGNED NOT NULL,
    direction ENUM('incoming', 'outgoing') NOT NULL,
    reference VARCHAR(20) NOT NULL,
    sequence_year SMALLINT UNSIGNED NOT NULL,
    sequence_number INT UNSIGNED NOT NULL,
    subject VARCHAR(255) NOT NULL,
    summary TEXT NULL,
    correspondent_id INT UNSIGNED NOT NULL,
    department_id INT UNSIGNED NULL,
    channel ENUM('postal', 'email', 'hand_delivered', 'fax', 'registered', 'other') NOT NULL,
    priority ENUM('low', 'normal', 'high', 'urgent') NOT NULL DEFAULT 'normal',
    confidentiality ENUM('public', 'internal', 'confidential', 'secret') NOT NULL DEFAULT 'internal',
    status ENUM('registered', 'assigned', 'in_progress', 'awaiting_reply', 'answered', 'closed', 'archived') NOT NULL DEFAULT 'registered',
    document_date DATE NULL,
    received_at DATETIME NULL,
    sent_at DATETIME NULL,
    due_date DATE NULL,
    external_reference VARCHAR(100) NULL,
    closed_at DATETIME NULL,
    created_by INT UNSIGNED NOT NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_mails_sequence (site_id, direction, sequence_year, sequence_number),
    UNIQUE KEY uq_mails_reference (site_id, reference),
    KEY idx_mails_site_status_due (site_id, status, due_date),
    KEY idx_mails_site_received (site_id, received_at),
    KEY idx_mails_site_sent (site_id, sent_at),
    KEY idx_mails_correspondent (correspondent_id),
    KEY idx_mails_department (department_id),
    CONSTRAINT fk_mails_site FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT fk_mails_correspondent FOREIGN KEY (correspondent_id) REFERENCES correspondents (id),
    CONSTRAINT fk_mails_department FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT fk_mails_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_mails_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
